version: '3'

includes:
  utopia: ./taskfiles/utopia.yaml
  format: ./taskfiles/format.yaml
  assets: ./taskfiles/assets.yaml
  build: ./taskfiles/build.yaml
  dev: ./taskfiles/dev.yaml

tasks:
  default:
    - task -a

  setup:
    cmds:
      - curl https://get.volta.sh | bash
      - volta install node
      - volta install pnpm

  install:
    source: package.json
    generates:
      - pnpm-lock.yaml
    cmds:
      - echo "Installing package.json deps"
      - pnpm install

  dev:
    deps: [install, assets:create, utopia:tokens, format:src]
    cmds:
      - task dev:start

  build:deploy:
    deps: [install, assets:create]
    cmds:
      - task build:site
      - task format:dist

  build:
    deps: [clean, build:deploy, utopia:tokens, format:src]
    cmds:
      - task build:site
      - task format:dist

  resources:watch:
    deps: [assets:create, utopia:tokens]
    watch: true

  clean:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist
